# Claude Ecosystem -- OpenAI Codex Setup (Windows)
# Generates AGENTS.md for a project from ecosystem sources.
# Run as: powershell -File setup-codex.ps1 D:\CODING\my-project

param(
  [Parameter(Mandatory = $true, Position = 0)]
  [string]$ProjectPath
)

$EcosystemDir = $PSScriptRoot

# --- Source files -------------------------------------------
$Sources = @(
  @{
    Header = "## Coding Style"
    File   = Join-Path $EcosystemDir "rules\coding-style.md"
  },
  @{
    Header = "## Security Rules"
    File   = Join-Path $EcosystemDir "rules\security.md"
  },
  @{
    Header = "## Workflow & Quality Gates"
    File   = Join-Path $EcosystemDir `
      "adapters\shared\workflow-gates.md"
  },
  @{
    Header = "## Agent Roles & Development Principles"
    File   = Join-Path $EcosystemDir `
      "adapters\shared\agents-guide.md"
  }
)

$MarkerStart = "<!-- ecosystem-start -->"
$MarkerEnd   = "<!-- ecosystem-end -->"

# --- Helpers ------------------------------------------------
function Write-Step {
  param(
    [string]$Label,
    [string]$Message,
    [string]$Color = "Green"
  )
  Write-Host "  $Label " -ForegroundColor $Color -NoNewline
  Write-Host $Message
}

function Strip-TopHeader {
  param([string]$Content)
  # Remove the first line if it starts with "# "
  $lines = $Content -split "`n"
  if ($lines.Count -gt 0 -and $lines[0] -match '^# ') {
    $lines = $lines[1..$($lines.Count - 1)]
  }
  # Remove leading blank lines after header removal
  while (
    $lines.Count -gt 0 -and
    [string]::IsNullOrWhiteSpace($lines[0])
  ) {
    $lines = $lines[1..$($lines.Count - 1)]
  }
  return ($lines -join "`n")
}

# --- Main ---------------------------------------------------
Write-Host "Claude Ecosystem -- Codex Setup" `
  -ForegroundColor Cyan
Write-Host "Ecosystem repo: $EcosystemDir"
Write-Host "Target project: $ProjectPath"
Write-Host ""

# Validate project path
if (-not (Test-Path $ProjectPath -PathType Container)) {
  Write-Host "  ERROR Project path does not exist: $ProjectPath" `
    -ForegroundColor Red
  exit 1
}

# Validate all source files exist
foreach ($src in $Sources) {
  if (-not (Test-Path $src.File)) {
    Write-Host "  ERROR Source file not found: $($src.File)" `
      -ForegroundColor Red
    exit 1
  }
}

# Build ecosystem block content
Write-Step "BUILD" "Compiling AGENTS.md from ecosystem sources"

$parts = @()
$parts += $MarkerStart
$parts += "# Project Instructions"
$parts += ""
$parts += (
  "(Generated by claude-ecosystem." +
  " Do not edit between markers.)"
)

foreach ($src in $Sources) {
  $raw = Get-Content $src.File -Raw -Encoding utf8
  $body = Strip-TopHeader $raw

  $parts += ""
  $parts += $src.Header
  $parts += ""
  $parts += $body.TrimEnd()
}

$parts += ""
$parts += $MarkerEnd

$ecosystemBlock = $parts -join "`n"

# Write AGENTS.md
$agentsPath = Join-Path $ProjectPath "AGENTS.md"

if (Test-Path $agentsPath) {
  $existing = Get-Content $agentsPath -Raw -Encoding utf8

  $hasMarkers = (
    $existing.Contains($MarkerStart) -and
    $existing.Contains($MarkerEnd)
  )
  if ($hasMarkers) {
    # Replace content between markers (inclusive)
    Write-Step "UPDATE" `
      "Replacing ecosystem section in existing AGENTS.md"

    $pattern = [regex]::Escape($MarkerStart) +
      '[\s\S]*?' +
      [regex]::Escape($MarkerEnd)
    $updated = [regex]::Replace(
      $existing, $pattern, $ecosystemBlock
    )
    [System.IO.File]::WriteAllText(
      $agentsPath, $updated,
      [System.Text.UTF8Encoding]::new($false)
    )
  } else {
    # No markers -- backup and write fresh
    $backupPath = "$agentsPath.bak"
    Copy-Item -Path $agentsPath -Destination $backupPath
    $msg = "Existing AGENTS.md backed up to AGENTS.md.bak"
    Write-Step "BACK" $msg "Yellow"

    [System.IO.File]::WriteAllText(
      $agentsPath,
      $ecosystemBlock,
      [System.Text.UTF8Encoding]::new($false)
    )
    Write-Step "WRITE" `
      "AGENTS.md created (old file preserved)"
  }
} else {
  # No existing file -- write new
  [System.IO.File]::WriteAllText(
    $agentsPath,
    $ecosystemBlock,
    [System.Text.UTF8Encoding]::new($false)
  )
  Write-Step "WRITE" "AGENTS.md created"
}

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Generated:" -ForegroundColor Cyan
Write-Host "  $agentsPath"
Write-Host ""
Write-Host "Sections included:" -ForegroundColor Cyan
foreach ($src in $Sources) {
  Write-Host "  - $($src.Header -replace '^## ', '')"
}
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review AGENTS.md in your project root"
Write-Host "  2. Add project-specific instructions outside" `
  "the markers"
Write-Host "  3. Run again to update ecosystem sections" `
  "without losing your edits"
