#!/bin/bash
# Claude Ecosystem -- OpenAI Codex Setup (Linux/Mac)
# Generates AGENTS.md for a project from ecosystem sources.
# Run as: bash setup-codex.sh /path/to/my-project

set -e

ECOSYSTEM_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_PATH="${1:?Usage: bash setup-codex.sh <project-path>}"

# --- Source files -----------------------------------------
SOURCES_HEADERS=(
  "## Coding Style"
  "## Security Rules"
  "## Workflow & Quality Gates"
  "## Agent Roles & Development Principles"
)
SOURCES_FILES=(
  "$ECOSYSTEM_DIR/rules/coding-style.md"
  "$ECOSYSTEM_DIR/rules/security.md"
  "$ECOSYSTEM_DIR/adapters/shared/workflow-gates.md"
  "$ECOSYSTEM_DIR/adapters/shared/agents-guide.md"
)

MARKER_START="<!-- ecosystem-start -->"
MARKER_END="<!-- ecosystem-end -->"

# --- Helpers ----------------------------------------------
info() {
  echo -e "  \033[32m$1\033[0m $2"
}

warn() {
  echo -e "  \033[33m$1\033[0m $2"
}

err() {
  echo -e "  \033[31mERROR\033[0m $1" >&2
  exit 1
}

strip_top_header() {
  # Remove first line if it starts with "# ", then
  # remove leading blank lines
  local content="$1"
  local first_line
  first_line="$(echo "$content" | head -n 1)"

  if echo "$first_line" | grep -q '^# '; then
    content="$(echo "$content" | tail -n +2)"
  fi

  # Remove leading blank lines
  while true; do
    first_line="$(echo "$content" | head -n 1)"
    if [ -z "$first_line" ]; then
      content="$(echo "$content" | tail -n +2)"
    else
      break
    fi
  done

  echo "$content"
}

# --- Main -------------------------------------------------
echo -e "\033[36mClaude Ecosystem -- Codex Setup\033[0m"
echo "Ecosystem repo: $ECOSYSTEM_DIR"
echo "Target project: $PROJECT_PATH"
echo ""

# Validate project path
if [ ! -d "$PROJECT_PATH" ]; then
  err "Project path does not exist: $PROJECT_PATH"
fi

# Validate all source files exist
for file in "${SOURCES_FILES[@]}"; do
  if [ ! -f "$file" ]; then
    err "Source file not found: $file"
  fi
done

# Build ecosystem block content
info "BUILD" \
  "Compiling AGENTS.md from ecosystem sources"

BLOCK="$MARKER_START
# Project Instructions

(Generated by claude-ecosystem. Do not edit between markers.)"

for i in "${!SOURCES_FILES[@]}"; do
  raw="$(cat "${SOURCES_FILES[$i]}")"
  body="$(strip_top_header "$raw")"

  BLOCK="$BLOCK

${SOURCES_HEADERS[$i]}

$body"
done

BLOCK="$(printf '%s' "$BLOCK" | sed -e 's/[[:space:]]*$//')
$MARKER_END"

# Write AGENTS.md
AGENTS_PATH="$PROJECT_PATH/AGENTS.md"

if [ -f "$AGENTS_PATH" ]; then
  existing="$(cat "$AGENTS_PATH")"

  if echo "$existing" | grep -qF "$MARKER_START" && \
     echo "$existing" | grep -qF "$MARKER_END"; then
    # Replace content between markers (inclusive)
    info "UPDATE" \
      "Replacing ecosystem section in existing AGENTS.md"

    # Extract before start marker and after end marker
    before="$(echo "$existing" \
      | sed -n "1,/${MARKER_START}/{ /${MARKER_START}/!p }")"
    after="$(echo "$existing" \
      | sed -n "/${MARKER_END}/,\${ /${MARKER_END}/!p }")"

    # Rebuild file
    {
      if [ -n "$before" ]; then
        printf '%s\n' "$before"
      fi
      printf '%s' "$BLOCK"
      if [ -n "$after" ]; then
        printf '\n%s' "$after"
      fi
    } > "$AGENTS_PATH"
  else
    # No markers -- backup and write fresh
    cp "$AGENTS_PATH" "$AGENTS_PATH.bak"
    warn "BACK" \
      "Existing AGENTS.md backed up to AGENTS.md.bak"

    printf '%s\n' "$BLOCK" > "$AGENTS_PATH"
    info "WRITE" "AGENTS.md created (old file preserved)"
  fi
else
  # No existing file -- write new
  printf '%s\n' "$BLOCK" > "$AGENTS_PATH"
  info "WRITE" "AGENTS.md created"
fi

echo ""
echo -e "\033[32mSetup complete!\033[0m"
echo ""
echo -e "\033[36mGenerated:\033[0m"
echo "  $AGENTS_PATH"
echo ""
echo -e "\033[36mSections included:\033[0m"
for header in "${SOURCES_HEADERS[@]}"; do
  echo "  - ${header#\#\# }"
done
echo ""
echo -e "\033[36mNext steps:\033[0m"
echo "  1. Review AGENTS.md in your project root"
echo "  2. Add project-specific instructions" \
  "outside the markers"
echo "  3. Run again to update ecosystem sections" \
  "without losing your edits"
